const path = require("path");
const fs = require("fs");

// Support Cloud Run / dynamic PORT environment variable (defaults to 3000)
const port = parseInt(process.env.PORT || "3000", 10);
const hostname = process.env.HOSTNAME || "0.0.0.0";
process.env.PORT = String(port);
process.env.HOSTNAME = hostname;

console.log(`[Bonnivo Server] Initializing production server on ${hostname}:${port}...`);

// Priority 1: Next.js Standalone server generated by monorepo build
const standaloneServerPath = path.join(__dirname, ".next", "standalone", "apps", "web", "server.js");
const rootStandaloneServerPath = path.join(__dirname, ".next", "standalone", "server.js");

if (fs.existsSync(standaloneServerPath)) {
  console.log(`[Bonnivo Server] Launching Next.js standalone server from ${standaloneServerPath}`);
  require(standaloneServerPath);
} else if (fs.existsSync(rootStandaloneServerPath)) {
  console.log(`[Bonnivo Server] Launching Next.js root standalone server from ${rootStandaloneServerPath}`);
  require(rootStandaloneServerPath);
} else {
  console.log(`[Bonnivo Server] Fallback: Launching via next start CLI...`);
  const { spawn } = require("child_process");
  const webDir = path.join(__dirname, "apps", "web");
  const cwd = fs.existsSync(path.join(webDir, ".next")) ? webDir : __dirname;

  const child = spawn("npx", ["next", "start", "-H", hostname, "-p", String(port)], {
    stdio: "inherit",
    shell: true,
    cwd,
    env: { ...process.env, PORT: String(port), HOSTNAME: hostname },
  });

  child.on("exit", (code) => {
    process.exit(code || 0);
  });
}
